### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by cyjouc** [microsoft/Deep3DFaceReconstruction#107]
what the version of cuda? the python preprocess_img.py occure the error:
failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED

**Comment by cyjouc** [comment]
preprocess_img.py:74: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (wwhich is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray  trans_params = np.array([w0,h0,102.0/s,t[0],t[1]])

**Comment by YuDeng** [comment]
The code should be able to run under both cuda9.0 and cuda10.0, with cudnn version higher than 7.5. You may check if your cudnn library is too old.

**Comment by cyjouc** [comment]
Hi,Mr.Deng,the error is solved by upgrade tensorflow 1.13.Now re-compie  the old version tf_mesh_renderer-master(bazel test ...) occur to the error:
tf_mesh_renderer-master/WORKSPACE:27:1: name 'http_archive' is not defined
loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl':
error loading package 'external': Could not load //external package?
Have you ever encountered these problem？

**Comment by YuDeng** [comment]
Sorry I have not encountered with the exact same error before.  However I do meet similar problems when compile the library with bazel. I fixed the error by using an old version of bazel to compile the library.  Hope it can help.

**Comment by cyjouc** [comment]
Hi，thanks for your helps.I have successfully passed the training process,.how can I visualizate the .mat output result? I try to show .obj result through the meshlab tool.

**Comment by Msj5** [comment]
> Hi，thanks for your helps.I have successfully passed the training process,.how can I visualizate the .mat output result? I try to show .obj result through the meshlab tool.

Congratulations for solving the problems.  Could you provide the usable "rasterize_triangles_kernel.so" file to 15071356159@126.com， or show me the version of tensorflow cuda cudnn bazel and python, thanks.

**Comment by YuDeng** [comment]
> Hi，thanks for your helps.I have successfully passed the training process,.how can I visualizate the .mat output result? I try to show .obj result through the meshlab tool.

The .mat files can be opened via matlab.

**Comment by cyjouc** [comment]
Hi,thanks for you,I success to visualizate the mat file.Can you add me WeChat(hicaicaihi for my wechat code)? I would like to ask more details about this model implementation.
